[manager]
manager1 ansible_host=3.90.131.106 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/d/Projects/DevOPs/final/devops_final/terraform/aws/final-devops-key.pem

[workers]
worker1 ansible_host=3.84.88.69 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/d/Projects/DevOPs/final/devops_final/terraform/aws/final-devops-key.pem
worker2 ansible_host=54.157.60.231 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/d/Projects/DevOPs/final/devops_final/terraform/aws/final-devops-key.pem

[swarm:children]
manager
workers
