[manager]
manager1 ansible_host=3.90.131.106 ansible_user=ubuntu swarm_manager_advertise_addr=10.0.1.172


[workers]
worker1 ansible_host=54.234.152.219 ansible_user=ubuntu swarm_worker_advertise_addr=10.0.1.155
worker2 ansible_host=34.230.68.66 ansible_user=ubuntu swarm_worker_advertise_addr=10.0.2.179

[swarm:children]
manager
workers
[all:vars]
ansible_ssh_private_key_file=~/.ssh/final-devops-key.pem
ansible_python_interpreter=/usr/bin/python3
